### ISSUE TITLE
Allow passing functions as arguments to set

### ISSUE THREAD

**Issue by perrin4869** [planttheidea/unchanged#14]
I suggest allowing something like this:

```js
const object = {
  foo: [
    {
      bar: 'baz'
    }
  ]
};

console.log(set('foo[0].bar', prev => prev + ' quz', object)); // {foo: [{bar: 'baz quz'}]}
```

I could submit a PR if you'd like, thanks :)

**Comment by planttheidea** [comment]
What is the use case that this solves / improves? And also, I'm assuming that would be run if value was a function, but what would you do if you actually wanted to assign a function as a value?

**Comment by perrin4869** [comment]
Thanks for the response!
As for the second problem, I actually don't have an answer =/
The usecase that I'm thinking about is the following. I have this function that creates 3 redux action creators:

```js
const actions = getActions('PREFIX_');
```

That returns an object:

```js
{
  request: () => ({ type: 'PREFIX_REQUEST' }),
  response: (payload) => ({ type: 'PREFIX_RESPONSE', payload: body })
  error: (err) => ({ type: 'PREFIX_ERROR', payload: err }),
}
```

What I would like to do, is use `set` here to change the response action creator to be the following:

```js
const actions = set('response', original => body => ({
  ...original(body),
  extraKey: 'foo',
}), getActions());
```

I'm not sure this usecase justifies the added complexity, that's up to you to decide :)

**Comment by planttheidea** [comment]
Ah so this is actually a good one because it has both attributes in it! You are trying to assign a function to the `response` property, and as shown in the example the only way to do that with this change is to have a function that returns a function (regardless of whether you use the parameter passed or not). In that sense I'm probably going to say no, because you are making existing functionality more difficult in a breaking way, when you just as easily use your existing function example (tweaked) without changes to the library to accomplish it.

```javascript
const getEnhancedResponse = original => body => ({...original.response(body), extraKey: 'foo'});
...
const actions = getActions();
const enhancedActions = set('response', getEnhancedResponse(actions), actions);
```

I'll keep this issue open in case further discussion is had (maybe there is an idea I'm not seeing), but the breaking of existing functionality makes this kind of a non-starter for what would basically just be a convenience.

**Comment by perrin4869** [comment]
Yeah I agree with you, I'll close this then, thanks!
