### ISSUE TITLE
v2.0.0 breaks old behavior

### ISSUE THREAD

**Issue by alexesDev** [planttheidea/unchanged#33]
Short example:
```js
const obj = Object.create(null);
set(obj, 'key', 'value')
// TypeError: Cannot convert object to primitive value
```
`parse` from `query-string` uses `Object.create(null)` for example.

**Comment by planttheidea** [comment]
The order of arguments that you are using has never been supported ... It was always object-last.

`set('key', 'value', obj);`

I'll check if things work as expected with a pure object with that order.

**Comment by alexesDev** [comment]
@planttheidea yep, sorry
```js
const obj = Object.create(null);
set('key', 'value', obj)
// TypeError: Object prototype may only be an Object or null: undefined
```

**Comment by planttheidea** [comment]
No worries, you were spot on ... and this was a change in the code, originally I was using `Object.getPrototypeOf` to get the custom prototype but switched to `object.__proto__` because the performance difference is massive. It appears for pure objects that leads to `undefined` being used instead of `null`, which `Object.create` barks at.

The fix is easy (coalesce ... `object.__proto__ || null`). I'll add a test for this and release a patch shortly.

**Comment by planttheidea** [comment]
Alright, `2.0.1` has been published with the fix for this. If you have any more issues, let me know!
