### ISSUE TITLE
New npm release?

### ISSUE THREAD

**Issue by ryanzec** [planttheidea/unchanged#74]
Could we get a new npm release to account for all the package updates that have happened?

**Comment by planttheidea** [comment]
No updates to the runtime dependencies have occurred since the versions in `package.json`. Maybe I missed something, though; is there a specific update to a build dependency you think would have impact? I'm more than happy to do a patch, but if there is no difference in the consumed package then there wouldn't be any benefit.

**Comment by ryanzec** [comment]
Didn't notice they are all dev dependencies so that makes sense.
